[package]
name = "contessa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
path = "src/main.rs"
name = "cts"

[lib]
path = "src/lib.rs"
name = "contessa"

[dependencies]
rand = "0.8.5"
